### ISSUE TITLE
Errors in the tests when running coverage locally

### ISSUE THREAD

**Issue by Fishrock123** [nodejs/testing#45]
```
/usr/bin/python tools/test.py --mode=release -J \
		addons doctool inspector known_issues message pseudo-tty parallel sequential
[02:58|%  95|+ 1223|-   0]: release core_line_numbers match failed
line=0
expect=^punycode\.js\:42$
actual=punycode.js:11
=== release core_line_numbers ===
Path: message/core_line_numbers
punycode.js:11
 */function error(type){++__cov_72evqMnR0PdyYWn6$tPSHG2aAeE.f['1'];++__cov_72evqMnR0PdyYWn6$tPSHG2aAeE.s['17'];throw new RangeError(errors[type]);}/**
                                                                                                               ^

RangeError: Invalid input
    at error (punycode.js:11:118)
    at Object.decode (punycode.js:95:307)
    at Object.<anonymous> (/Users/Jeremiah/Documents/node/test/message/core_line_numbers.js:11:10)
    at Module._compile (module.js:98:1154)
    at Object.Module._extensions..js (module.js:99:286)
    at Module.load (module.js:81:967)
    at tryModuleLoad (module.js:79:2029)
    at Function.Module._load (module.js:79:1682)
    at Module.runMain (module.js:103:8)
    at run (bootstrap_node.js:74:1)
Command: out/Release/node /Users/Jeremiah/Documents/node/test/message/core_line_numbers.js
[02:58|%  95|+ 1223|-   1]: release error_exit match failed
line=2
expect=^\ \ throw\ new\ assert\.AssertionError\(\{$
actual=function fail(actual,expected,message,operator,stackStartFunction){++__cov_exLDdsBOrNFfDPc4AWo9nesRDE8.f['5'];++__cov_exLDdsBOrNFfDPc4AWo9nesRDE8.s['22'];throw new assert.AssertionError({message:message,actual:actual,expected:expected,operator:operator,stackStartFunction:stackStartFunction});}// EXTENSION! allows for well behaved errors defined elsewhere.
=== release error_exit ===
Path: message/error_exit
Exiting with code=1

assert.js:42
function fail(actual,expected,message,operator,stackStartFunction){++__cov_exLDdsBOrNFfDPc4AWo9nesRDE8.f['5'];++__cov_exLDdsBOrNFfDPc4AWo9nesRDE8.s['22'];throw new assert.AssertionError({message:message,actual:actual,expected:expected,operator:operator,stackStartFunction:stackStartFunction});}// EXTENSION! allows for well behaved errors defined elsewhere.
                                                                                                                                                          ^
AssertionError: 1 == 2
    at Object.<anonymous> (/Users/Jeremiah/Documents/node/test/message/error_exit.js:9:8)
    at Module._compile (module.js:98:1154)
    at Object.Module._extensions..js (module.js:99:286)
    at Module.load (module.js:81:967)
    at tryModuleLoad (module.js:79:2029)
    at Function.Module._load (module.js:79:1682)
    at Module.runMain (module.js:103:8)
    at run (bootstrap_node.js:74:1)
    at startup (bootstrap_node.js:33:325)
    at bootstrap_node.js:77:5707
Command: out/Release/node /Users/Jeremiah/Documents/node/test/message/error_exit.js
[03:55|% 100|+ 1280|-   2]: Done
make: *** [test] Error 1
```

Commands run:

(gcovr)
```
patch -p1 < "../testing-wg/coverage/gcovr-patches.diff"
```

(node)
```
patch -p1 < "../testing-wg/coverage/patches.diff"
npm i istanbul-merge@1.1.0
npm i nyc@8.0.0-candidate
test -x "./node_modules/.bin/nyc"
test -x "./node_modules/.bin/istanbul-merge"
"./node_modules/.bin/nyc" instrument lib/ lib_/
sed -e s~"'"lib/~"'"lib_/~g -i~ node.gyp
make test
```

cc @addaleax and @mhdawson ?

**Comment by addaleax** [comment]
Yeah, I think the message tests have always been kind of problematic under coverage, and I don’t think they are run as part of the coverage CI runs :/

**Comment by addaleax** [comment]
Oh and fwiw, for JS coverage only gcovr should be unnecessary, so you can skip that

**Comment by Trott** [comment]
Coverage is now in the main repo. Closing this. It can be opened in the main repo if it's still an issue. Thanks.
